name: Build and Store Artifact

permissions:
  contents: write

on: [push]
  # push:
  #   tags:
  #     - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install libs
        run: |
          npm install

      - name: Build project
        run: |
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist

      # - name: Publish artifact
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: dist/*.deb
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

